### ISSUE TITLE
GitHub should ask for "PAT" and not "Password"

### ISSUE THREAD

**Issue by AlexanderLanin** [microsoft/Git-Credential-Manager-Core#222]
Since OAuth is sometimes disabled on GitHub Enterprise the old form still needs to be maintained. 
It's currently asking for username/password which is basically just wrong. Username/password login is disabled on GitHub.
It should say username/PAT (Potentially with a hint how to generate a PAT and a link to `{domain}/settings/tokens/new`).

See https://github.com/microsoft/Git-Credential-Manager-Core/pull/171#issuecomment-728974236 for how the old dialog can currently be reached.

**Comment by AlexanderLanin** [comment]
Upon further investigation PAT doesn't work at all at the moment, does it?
The code [always](https://github.com/microsoft/Git-Credential-Manager-Core/blob/ba1fe717ce49f0eaa53e6cc2f7e40988119a9622/src/shared/GitHub/GitHubHostProvider.cs#L99) tries to create a PAT which fails considering the user has already entered a PAT.

Am I somehow wrong?

**Comment by mjcheetham** [comment]
> The code [always](https://github.com/microsoft/Git-Credential-Manager-Core/blob/ba1fe717ce49f0eaa53e6cc2f7e40988119a9622/src/shared/GitHub/GitHubHostProvider.cs#L99) tries to create a PAT which fails considering the user has already entered a PAT.

It shouldn't fail here. The call to `GeneratePersonalAccessTokenAsync` with a PAT as the password, will pass the PAT to the `authorizations` API endpoint, which _should_ return a 403 response with the error "This API can only be accessed with username and password Basic Auth".

We [handle this obscure case](https://github.com/microsoft/Git-Credential-Manager-Core/blob/ba1fe717ce49f0eaa53e6cc2f7e40988119a9622/src/shared/GitHub/GitHubRestApi.cs#L137-L153) and return the 'password' (the PAT) as-is, knowing it is a PAT directly. At least, we should handle this case. It's possible the GitHub server no longer returns this case since username/password access was removed from the API.

**Comment by mjcheetham** [comment]
The ability to enter a PAT explicitly for GHES (and GitHub.com) will be available on the next feature release of GCM Core.
PR #236 has been merged in.
