### ISSUE TITLE
Credential popups don't show any context information

### ISSUE THREAD

**Issue by johnendev** [microsoft/Git-Credential-Manager-Core#239]
When the credential manager pops up asking for credentials there is no context about which repository or program is requesting access.
I have some background tasks which perform git operations now and then, and sometimes windows decides to drop stored creds so I get the cred popups without any context or user interaction and it just seems a lot like phishing.

It should at least show something to identify which repo/program the creds are being requested for before the user takes action.

**Comment by mjcheetham** [comment]
Would require support from the MSAL library; requested this change here:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2397

**Comment by mjcheetham** [comment]
Reopening because GCM is not using the WebView2 embedded browser still due to an oversight whereby we are not calling `WithDesktopFeatures()` on MSAL that is required to opt-in to using WebView2 on .NET Framework.

_HOWEVER_.. we still cannot add this feature because of some issues with loading the WebView2 runtime:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2633

**Comment by mjcheetham** [comment]
PR to add the window title to the WebView1 window: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2936

**Comment by mjcheetham** [comment]
PR #512 should allow us to set the window title on the embedded browser window, which once merged, will be in the next release.
