### ISSUE TITLE
Auto-detect Bitbucket Server/On-Prem instances

### ISSUE THREAD

**Issue by mjcheetham** [microsoft/Git-Credential-Manager-Core#267]
As of #262 we have the ability to do some simple probing of the remote URL to detect on-prem/self hosted instances of Git host providers (like GitHub Enterprise Server).

We should hopefully be able to do something similar with Bitbucket's on-prem offering. We ideally just need a well-known header to look out for. (for GHES we look for `X-GitHub-Request-Id` for example)

Any ideas here @mminns ?

**Comment by mminns** [comment]
Sorry I missed the mention, I'll take a look.

**Comment by mminns** [comment]
I don't think I can assign this to myself?

FYI I'm hoping to be able to start contributing to the project again.

**Comment by mminns** [comment]
So it looks like we can use `X-AREQUESTID` .

It isn't Bitbucket specific but it is Atlassian specific. Since GCMC is called by Git and Git determines that information from the local git repository I think that is OK.

I'm just playing with it https://github.com/microsoft/Git-Credential-Manager-Core/commit/c359b4539c1622e7f171b4137b3ccc24fc215cf8

**Comment by mjcheetham** [comment]
Feature implemented in #373, thanks @mminns! This will go out in the next release 😁

**Comment by mjcheetham** [comment]
Released in 2.0.498
