### ISSUE TITLE
Add Support for a MSYS2 Shell

### ISSUE THREAD

**Issue by danyeaw** [microsoft/Git-Credential-Manager-Core#389]
I have Git-for-Windows installed and on my path with a MINGW64/MSYS2 shell. I installed Git-Credential-Manager-Core using the normal Windows installation script. Furthermore, I also added `/c/Users/dan/AppData/Local/Programs/GITCRE~1` to my MSYS2 PATH, and git-credential-manager-core launches successfully. 

My global config for git is set with `credential.helper=manager-core`. Whenever I try to commit a change it always brings up pinentry which is a required executable to have pacman installed in MSYS2. I have also tried setting `credential.credentialstore` using secretservice with libsecret installed and gpg with pass installed. Nothing seems to get CRM Core to work with git.

**Comment by vtbassmatt** [comment]
On Windows, we support [WSL](https://docs.microsoft.com/en-us/windows/wsl/about) and Git Bash. MSYS2 isn't something we can commit to supporting. (Kudos to anyone who gets it working, of course, and feel free to share that learning here!)

**Comment by superctr** [comment]
To get credential-manager to work in MSYS2, download the latest zipped release and extract the contents to `usr/bin` in your MSYS2 install folder (same directory as git et al). Then run `git config --global credential.helper manager-core`.

**Comment by eduarddejong** [comment]
I did it!
Here is how I got it working: make a symbolic link to the entire directory of the application and make use of that, to create a path without spaces in it (directly using the original path `/c/Program Files/Git/mingw64/bin` does not seem to work at all).

First, open a PowerShell as administrator, and enter the following command for :
`New-Item -ItemType SymbolicLink -Path 'C:\msys64\opt\git-for-windows-mingw64-bin' -Target 'C:\Program Files\Git\mingw64\bin'`
(of course you can also use the old `mklink` command of Windows, but I just prefer the modern powershell way).
This asumes that both paths exist and you have both Git for Windows and MSYS2 installed on those default locations, change them according to your needs.

Next, add the following 2 lines to your .gitconfig file in you MSYS2 homefolder:
```
[credential]
	helper = /opt/git-for-windows-mingw64-bin/git-credential-manager
[credential "https://dev.azure.com"]
	useHttpPath = true
```

Note that directly using a symlink to only the git-credential-manager binary does not work, because it's going to result in an error about missing libraries. A .NET application (since that's what it is) searches for libraries in the same folder, so it needs to have that context around.

**Comment by zhangxiaoxing** [comment]
I merged @superctr and @eduarddejong 's suggestion (zip file extract to /usr/bin, then helper=/usr/bin/git-credential-manager) and it worked. I guess I'll update by extract new files periodically; still beats type in credentials every time.
