### ISSUE TITLE
Failed to write credential: The stub received bad data

### ISSUE THREAD

**Issue by maliksahil** [microsoft/Git-Credential-Manager-Core#444]
**Which version of GCM Core are you using?**

From a terminal, run `git-credential-manager-core --version` and paste the output.

The version that is bundled with git 2.33.02

**Which Git host provider are you trying to connect to?**

* [ x] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [ x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [x ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [ ] Not applicable
* [ x] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

A clear and concise description of what happens. For example: exception is thrown, UI freezes, etc.

We get the following error,
C:\xxx\AD\MSA\Login>git pull
Failed to write credential: The stub received bad data
From xxxx
* [new branch] xxxTest -> origin/xxx/Test
* [new branch] test -> origin/test
Already up to date.

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

**Comment by mjcheetham** [comment]
> The stub received bad data

This error comes from the Windows credential manager APIs (accessed via functions defined in `wincred.h`), specifically [`CredWriteW`](https://docs.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credwritew) in this case.

This happens when the token/password to be stored is over 512 bytes in length (note that the _real_ max length is actually 5*512=2560 bytes, as defined in the `wincred.h` header file(!)).

I know from conversations offline that you have opened this issue regarding the WAM/Windows Broker experimental feature.
Please can you include a copy of the `GCM_TRACE` output as per the issue template:

> Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

> The version that is bundled with git 2.33.02

For the benefit of others, this is referring to the GCM bundled with Git for Windows 2.33.0 (2), that is to say, GCM version 2.0.498.54650.

**Comment by vtbassmatt** [comment]
@maliksahil can you provide `GCM_TRACE`/`GIT_TRACE` traces? We need that to troubleshoot the issue.

**Comment by mjcheetham** [comment]
Closing as without trace logs we cannot investigate or reproduce, and there's been no response.
