### ISSUE TITLE
WebView2Loader assembly has a bad signature

### ISSUE THREAD

**Issue by mjcheetham** [microsoft/Git-Credential-Manager-Core#462]
We've had several complaints that the WebView2Loader.dll binary that ships inside of GCM causes signing problems. First for getting Git for Windows submitted to the Microsoft Store (https://github.com/git-for-windows/git/issues/1146#issuecomment-883066153), and more recently problems with GitHub Desktop.

The WebView2Loader.dll comes in from our dependency on MSAL.NET's `Microsoft.Identity.Client.Desktop` package. We need that package on Windows to bring in support for WAM when targeting .NET Framework (as apposed to `netX-windows*`).

The annoying thing is that we don't even use WebView2 because of various problems with it. We tried to move to .NET 5 on Window in the past and this resulted in an unacceptable bloat in binary size. When we turned all the optimisations/linking up to the highest level we only managed to reduce binary size a small amount, but broke things like UI.

We may have to drop WAM entirely. cc: @bgavrilMS

**Comment by bgavrilMS** [comment]
We can split webview2 out of msal and msal.desktop

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Matthew John Cheetham ***@***.***>
Sent: Wednesday, September 22, 2021 9:31:18 AM
To: microsoft/Git-Credential-Manager-Core ***@***.***>
Cc: Bogdan Gavril ***@***.***>; Mention ***@***.***>
Subject: [microsoft/Git-Credential-Manager-Core] WebView2Loader assembly has a bad signature (#462)


We've had several complaints that the WebView2Loader.dll binary that ships inside of GCM causes signing problems. First for getting Git for Windows submitted to the Microsoft Store (git-for-windows/git#1146 (comment)<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgit-for-windows%2Fgit%2Fissues%2F1146%23issuecomment-883066153&data=04%7C01%7CBogdan.Gavril%40microsoft.com%7C1660b4c348244dc3f5c508d97da359c3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637678962825898996%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EVyqLTP9j%2F89XC4B88XtXBWxpVtwaUbwp7DHN%2FIVoRk%3D&reserved=0>), and more recently problems with GitHub Desktop.

The WebView2Loader.dll comes in from our dependency on MSAL.NET's Microsoft.Identity.Client.Desktop package. We need that package on Windows to bring in support for WAM when targeting .NET Framework (as apposed to netX-windows*).

The annoying thing is that we don't even use WebView2 because of various problems with it. We tried to move to .NET 5 on Window in the past and this resulted in an unacceptable bloat in binary size. When we turned all the optimisations/linking up to the highest level we only managed to reduce binary size a small amount, but broke things like UI.

We may have to drop WAM entirely. cc: @bgavrilMS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FbgavrilMS&data=04%7C01%7CBogdan.Gavril%40microsoft.com%7C1660b4c348244dc3f5c508d97da359c3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637678962825908952%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3q3hK7woPro7pM1OW%2BYc7xV0uJ6gspJJgBri5rfb5WA%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FGit-Credential-Manager-Core%2Fissues%2F462&data=04%7C01%7CBogdan.Gavril%40microsoft.com%7C1660b4c348244dc3f5c508d97da359c3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637678962825918909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RR4TjgnYhdU12lkNRGXr7nwGkAIitNHBnAVAYPtimZ8%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAC5UN2BY6O4ZYWZZ2ALWNL3UDGH5NANCNFSM5EQXWDWQ&data=04%7C01%7CBogdan.Gavril%40microsoft.com%7C1660b4c348244dc3f5c508d97da359c3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637678962825918909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dFm%2B8arwh7yC6NXyUvZQwfjfUH2mqHEvDQ05Ym7T2Pk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CBogdan.Gavril%40microsoft.com%7C1660b4c348244dc3f5c508d97da359c3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637678962825928865%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zQe8pB%2FyumG4XyEQpb6G4Y1ly2%2FFkzIARDXI7j6hh58%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CBogdan.Gavril%40microsoft.com%7C1660b4c348244dc3f5c508d97da359c3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637678962825928865%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aeueiQIF14fRxO9MhRr48eJH%2FKjzDXFsccx8gYj1gGA%3D&reserved=0>.

**Comment by mjcheetham** [comment]
It looks like this is less a problem with the WebView2Loader binary, nor the GCM distributed copy, but the Git for Windows package!

https://github.com/git-for-windows/git/issues/3332#issuecomment-887298829

Looks like Git for Windows' build was stripping off the PE signature and causing an invalid signature. This has been fixed in https://github.com/git-for-windows/build-extra/pull/368
