### ISSUE TITLE
GCM Core: Why don't you offer the most basic usability?

### ISSUE THREAD

**Issue by schittli** [microsoft/Git-Credential-Manager-Core#477]
Hello

Since the beginning, the usability of Microsoft Windows Git Credential Manager is a nightmare because even for the most important two or three use cases you have to ask Google how to solve the problem.

Therefore, this proposal is very trivial and I bet that it does not even involve much work:
# Suggestion: Please ad the most basic usability to GCM Core

### 1. Commandline help for `git credential-manager-core` should be complete
I'm pretty sure that one or two additional lines here would help thousands of users a lot. Or is this help actually complete?:
```
git credential-manager-core get -?
get:
  [Git] Return a stored credential
Usage:
  git-credential-manager-core get [options]
Options:
  -?, -h, --help    Show help and usage information
```
To help you solve the puzzle: pretty sure there are more [options]. Otherwise, the command makes zero sense.

### 2. Usability 'feature': Please allow `git credential-manager-core get …` to list all available credentials
To inspire you why this might be helpful: it happens from time to time that a Git repository access doesn't work. With such a sophisticated command you could very quickly and easily find out if the credential is there at all. Smart, isn't it?

### 3. Usability 'feature': Please explain how to use `git credential-manager-core store -?` 
Of course, the use case here is also very tricky, so here is an example:
When cloning a public read-only Git repository, a Git client does not ask for the credential/access token. Now it gets exciting: if the user wants to write data to the repository later with the Git client, then most Git clients do not ask for the credential either, but simply report an error.

... and so starts the nightmare mentioned at the beginning when dealing with git credentials under Microsoft Windows: where and how can we add credential/access token for a specific git repository??

These are 3 very simple tasks that only make usable what is already there. 

It would be great if Microsoft's GCM Core would not be developed so lovelessly and the development would not stop at 98% of the work. A tiny bit more work - and the tool could be great.

Of course, users could start studying `git config` and `.gitconfig` but if there is something called 'Microsoft Git Credential Manager' which already has most functions, then it's possible that it offers some abstraction 😄 

Thanks a lot!, kind regards,
Thomas

**Comment by vtbassmatt** [comment]
Hi @schittli - thanks for your thoughts. I'll direct your attention to the [`get` and `store` commands documentation](https://github.com/microsoft/Git-Credential-Manager-Core/blob/main/docs/usage.md#get--store--erase). As you'll see there, what you're asking for isn't necessary and wouldn't help. Those commands are how GCM Core [communicates with Git](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage), not commands that a user needs to understand or type.

On Windows, GCM Core uses the Windows Credential Manager as its [default backing store](https://github.com/microsoft/Git-Credential-Manager-Core/blob/main/docs/credstores.md#windows-credential-manager). I'm sure you can see why we don't want to be in the business of reimplementing simple management of raw credentials, since such a tool ships with the operating system.

If a Git client fails to request credentials on push, feel free to file an issue about it. We might be able to help you troubleshoot; given the interaction between client, server, and GCM Core, the problem is likely not in GCM Core's control.
