### ISSUE TITLE
New "info: detecting host provider for 'https://example.com'..." message after upgrading to git version 2.33.1.windows.1

### ISSUE THREAD

**Issue by gpakosz** [microsoft/Git-Credential-Manager-Core#492]
Hello,

After upgrading to Git For Windows version `2.33.1`, we started seeing new messages on `stderr` as well as slow downs.

```
gpakosz@DES-00703 MINGW64 /d/Projects/xxx (master)
$ git --version
git version 2.33.1.windows.1

gpakosz@DES-00703 MINGW64 /d/Projects/xxx (master)
$ git fetch -p
info: detecting host provider for 'https://scm.corp.example.com/'...
info: detecting host provider for 'https://scm.corp.example.com/'...
info: detecting host provider for 'https://scm.corp.example.com/'...
```

Even though I landed on https://github.com/microsoft/Git-Credential-Manager-Core/blob/main/docs/autodetect.md, I still don't understand what this auto-detection of host provider is for.

Can you please elaborate on why the core credential manager needs to be aware of the application running on the remote server? What's the link with the Git protocol and authentication?

We also noticed the portable version of Git which uses `git-credential-wincred.exe` doesn't exhibit this behavior while working perfectly.

Using
```
git config --global credential.scm.corp.example.com.provider generic
```
or
```
git config --global credential.scm.corp.example.com.provider bitbucket
```
doesn't seem to end up with other observable side effect than the suppression of the messages.

Finally note that our remote repositories are handled by an on premise Bitbucket Server instance which is behind a reverse proxy. A `HEAD` request exhibits the [`X-AREQUESTID` header you're looking for](https://github.com/microsoft/Git-Credential-Manager-Core/blob/1f926e42c40db15e3fab0c68a7a5c3aabd416ce7/src/shared/Atlassian.Bitbucket/BitbucketHostProvider.cs#L68):
```
curl -I https://scm.corp.example.com
HTTP/1.1 302
Server: nginx/1.14.2
Date: Thu, 14 Oct 2021 10:14:14 GMT
Connection: keep-alive
X-AREQUESTID: @1WFLNF3x734x12390371x1
x-xss-protection: 1; mode=block
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
Pragma: no-cache
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache
Cache-Control: no-store
Location: https://scm.corp.example.com/repos?visibility=public
Content-Language: en-US
Strict-Transport-Security: max-age=63072000; includeSubdomains; preload
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
```
My understanding is that [`providers.TryGetFirst(x => x.IsSupported(probeResponse), out match)`](https://github.com/microsoft/Git-Credential-Manager-Core/blob/1f926e42c40db15e3fab0c68a7a5c3aabd416ce7/src/shared/Microsoft.Git.CredentialManager/HostProviderRegistry.cs#L202) calls into [`BitbucketHostProvider.IsSupported()`](https://github.com/microsoft/Git-Credential-Manager-Core/blob/1f926e42c40db15e3fab0c68a7a5c3aabd416ce7/src/shared/Atlassian.Bitbucket/BitbucketHostProvider.cs#L60) after other providers.

All in all, it seems too bad this auto detection is needed at all and done in sequence.

Thanks.

**Comment by mjcheetham** [comment]
@gpakosz:
 
> I still don't understand what this auto-detection of host provider is for.

> Can you please elaborate on why the core credential manager needs to be aware of the application running on the remote server? What's the link with the Git protocol and authentication?

In order to provide the best authentication experience, GCM needs to know what sort of Git hosting provider you're using. For example, is this GitHub.com, Azure DevOps, a GitHub Enterprise Server or Bitbucket Server instance?

For the "cloud" providers like GitHub.com or Azure DevOps we can simply look at the remote URL to see "github.com" or "dev.azure.com" and route to their preferred (or even **required**) authentication protocols (for example OAuth2, or OpenID Connect).

However, for the self-hosted ("on-prem") versions we don't know! The remote URL isn't any use to us since this can be named anything or even a local IP address. Also due to the limitation in the design, Git doesn't surface any HTTP response headers to us, only the host name!

GCM first checks all the supported host providers by matching the host name to the known cloud name:

```text
--> Is the host name "bitbucket.org"?
--> Is the host name "github.com"?
--> Is the host name "dev.azure.com"?
```

If we reach this point, we then perform a  HTTP `HEAD` request against the remote URL to see what comes back.
Each host provider is asked again if it recognises the response headers.

```text
--> Does the Bitbucket provider recognise <headers>?
--> Does the GitHub provider recognise <headers>?
--> Does the Azure Repos provider recognise <headers>?
```

If we get all the way to this point, we don't know anything about the host provider and so fall to a "generic" solution.
The generic provider just prompts for a username and password and doesn't do anything special.

> We also noticed the portable version of Git which uses git-credential-wincred.exe doesn't exhibit this behavior while working perfectly.

The `wincred` credential helper doesn't do any of the above. It just checks if theres a store credential based on the hostname, and if not, prompts for a simple username/password.

> [Setting the credential.provider option] doesn't seem to end up with other observable side effect than the suppression of the messages.

When setting the provider option GCM does not do any of the above logic to determine the provider; you have told us to go directly to the "generic" or "bitbucket" provider.

> All in all, it seems too bad this auto detection is needed at all and done in sequence.

I agree! The problem is trying to strike the right balance. Git doesn't tell the credential helpers nearly enough information to be able to "know" what sort of authentication protocol to use beyond "I need a password for example.com".

In an ideal world, Git would provide helpers like GCM with the HTTP authentication challenge (the `WWW-Authenticate` headers for example) and we could go directly to the correct credential authority.

If we didn't perform any of the auto-detection logic, then many people using on-prem servers like GitHub Enterprise Server or Bitbucket Server would need to configure GCM (with the `credential.provider` setting) to tell us "git.mycompany.com is actually a GHES instance" ahead of time.

@lnu:

> The "detecting" message could be silent. Is it really an error?:

Writing optional/informational messages to the Standard Error stream is a common practice in the Git ecosystem. The Standard Output stream is often parsed for information, which we don't want to break.

In credential helper case, the stdout stream is being used to communicate back to the Git process.

Given extra noise it generates (for not much value), I think we can consider removing the `info: detecting host provider for 'host'...` messages.

**Comment by mminns** [comment]
No, Bitbucket DC does not currently support OAuth 2.

**Comment by gpakosz** [comment]
While I'm at it, I have yet another question: why do we pay this auto-detection tax every time we `git fetch` even though the Windows' credentials manager has proper authentication information available?

**Comment by gpakosz** [comment]
@mjcheetham Does it make sense that I open another issue for the question above?

> why do we pay this auto-detection tax every time we git fetch even though the Windows' credentials manager has proper authentication information available?

Thanks

**Comment by RPitt** [comment]
_I know this issue is closed but I'm unsure where else to put this..._

The auto-detection strategy here is really anoying when used with git servers that are not auto-detected.
In that case there are several roundtrips before it all fails and falls back to generic, costing precious seconds.
